--------------------------------------------------------
--  DDL for Table TBLPOSITIONS
--------------------------------------------------------

  CREATE TABLE "NETFL"."TBLPOSITIONS" 
   (	"OID" NUMBER(4,0), 
	"POSITION" VARCHAR2(7 BYTE), 
	"SORTORDER" NUMBER(4,0), 
	"SIDEOFBALL" VARCHAR2(1 BYTE), 
	"POSITIONGROUP" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NETFL" ;
--------------------------------------------------------
--  DDL for Index IDX$$_34EF0004
--------------------------------------------------------

  CREATE INDEX "NETFL"."IDX$$_34EF0004" ON "NETFL"."TBLPOSITIONS" ("SORTORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NETFL" ;
--------------------------------------------------------
--  DDL for Index TBLPOSITIONS_PK21054928191100
--------------------------------------------------------

  CREATE UNIQUE INDEX "NETFL"."TBLPOSITIONS_PK21054928191100" ON "NETFL"."TBLPOSITIONS" ("OID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NETFL" ;
--------------------------------------------------------
--  DDL for Index TBLPOSITIONS_PK31052839173885
--------------------------------------------------------

  CREATE UNIQUE INDEX "NETFL"."TBLPOSITIONS_PK31052839173885" ON "NETFL"."TBLPOSITIONS" ("POSITION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NETFL" ;
--------------------------------------------------------
--  DDL for Trigger TR_TBLPOSITIONS_B_INS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "NETFL"."TR_TBLPOSITIONS_B_INS" BEFORE
INSERT ON "TBLPOSITIONS" FOR EACH ROW begin
  if :new.oid is null then
    select SEQ_TBLPOSITIONS_OID.nextval into :new.oid from dual;
  end if;
end;



/
ALTER TRIGGER "NETFL"."TR_TBLPOSITIONS_B_INS" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLPOSITIONS
--------------------------------------------------------

  ALTER TABLE "NETFL"."TBLPOSITIONS" MODIFY ("OID" NOT NULL ENABLE);
  ALTER TABLE "NETFL"."TBLPOSITIONS" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "NETFL"."TBLPOSITIONS" MODIFY ("SORTORDER" NOT NULL ENABLE);
  ALTER TABLE "NETFL"."TBLPOSITIONS" MODIFY ("SIDEOFBALL" NOT NULL ENABLE);
  ALTER TABLE "NETFL"."TBLPOSITIONS" ADD CONSTRAINT "TBLPOSITIONS_PK21054928191100" UNIQUE ("OID")
  USING INDEX "NETFL"."TBLPOSITIONS_PK21054928191100"  ENABLE;
  ALTER TABLE "NETFL"."TBLPOSITIONS" ADD CONSTRAINT "TBLPOSITIONS_PK31052839173885" PRIMARY KEY ("POSITION")
  USING INDEX "NETFL"."TBLPOSITIONS_PK31052839173885"  ENABLE;
