--------------------------------------------------------
--  DDL for Table TBLREALTEAMS
--------------------------------------------------------

  CREATE TABLE "NETFL"."TBLREALTEAMS" 
   (	"OID" NUMBER(2,0), 
	"TEAMABBREVIATION" VARCHAR2(3 BYTE), 
	"TEAMNAME" VARCHAR2(80 BYTE), 
	"BYEWEEK" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NETFL" ;
--------------------------------------------------------
--  DDL for Index SYS_C008731
--------------------------------------------------------

  CREATE UNIQUE INDEX "NETFL"."SYS_C008731" ON "NETFL"."TBLREALTEAMS" ("OID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NETFL" ;
--------------------------------------------------------
--  DDL for Trigger TR_TBLREALTEAMS_B_INS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "NETFL"."TR_TBLREALTEAMS_B_INS" BEFORE
INSERT ON "TBLREALTEAMS" FOR EACH ROW begin
  if :new.oid is null then
    select SEQ_TBLREALTEAMS_OID.nextval into :new.oid from dual;
  end if;
end;



/
ALTER TRIGGER "NETFL"."TR_TBLREALTEAMS_B_INS" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLREALTEAMS
--------------------------------------------------------

  ALTER TABLE "NETFL"."TBLREALTEAMS" MODIFY ("OID" NOT NULL ENABLE);
  ALTER TABLE "NETFL"."TBLREALTEAMS" MODIFY ("TEAMABBREVIATION" NOT NULL ENABLE);
  ALTER TABLE "NETFL"."TBLREALTEAMS" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "NETFL"."TBLREALTEAMS" ADD PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NETFL"  ENABLE;
